import { UserType } from '../../../models/user-type.enum';
import { User } from '../../../models/user.interface';

export const userMoch: User[] = [
    {
        userName: 'userName1',
        firstName: 'Aaa',
        lastName: 'Aaa',
        email: 'aaa@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName2',
        firstName: 'Bbb',
        lastName: 'Bbb',
        email: 'bbb@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName3',
        firstName: 'Ccc',
        lastName: 'Ccc',
        email: 'ccc@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName4',
        firstName: 'Ddd',
        lastName: 'Ddd',
        email: 'ddd@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName5',
        firstName: 'Eee',
        lastName: 'Eee',
        email: 'eee@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName6',
        firstName: 'Fff',
        lastName: 'Fff',
        email: 'fff@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName7',
        firstName: 'Ggg',
        lastName: 'Ggg',
        email: 'ggg@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName8',
        firstName: 'Hhh',
        lastName: 'Hhh',
        email: 'hhh@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName9',
        firstName: 'Iii',
        lastName: 'Iii',
        email: 'iii@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
    {
        userName: 'userName10',
        firstName: 'Jjj',
        lastName: 'Jjj',
        email: 'jjj@gmail.com',
        password: '1234567A',
        userType: UserType.Admin,
    },
];